#!/bin/bash
declare -a arr=("gradlew_gradle_linux" "gradlew_gradle_win")

for i in "${arr[@]}"
do

echo $i
HOME=`echo ~` docker run -v "$HOME/.gradle:/work" -v "$i:/home/user/.gradle" soywiz/kotlin-native-win:java8 /bin/bash -c "echo org.gradle.daemon=false > /home/user/.gradle/gradle.properties"
HOME=`echo ~` docker run -v "$HOME/.gradle:/work" -v "$i:/home/user/.gradle" soywiz/kotlin-native-win:java8 ls /home/user/.gradle/gradle.properties
done
