#!/bin/bash
HOME=`echo ~` docker run -it \
	-v "$PWD:/work" \
	-v "gradlew_gradle_linux:/root/.gradle" \
	-v "gradlew_konan_linux:/root/.konan" \
	-v "gradlew_m2:/root/.m2" \
	soywiz/kotlin-native-win:java11 \
	$*
