#!/bin/bash
HOME=`echo ~` docker run --rm -it \
	-v "$PWD:/work" \
	-v "gradlew_gradle_linux:/home/user/.gradle" \
	-v "gradlew_konan_linux:/home/user/.konan" \
	-v "gradlew_m2:/home/user/.m2" \
	soywiz/kotlin-native-win:java11 \
	$*
