#!/bin/bash
HOME=`echo ~` docker run -it \
	-v "$PWD:/work" \
	-v "gradlew_gradle_win:/root/.wine/drive_c/users/root/.gradle" \
	-v "gradlew_konan_win:/root/.wine/drive_c/users/root/.konan" \
	-v "gradlew_m2:/root/.wine/drive_c/users/root/.m2" \
	soywiz/kotlin-native-win:java11 \
	wine $*
